### ISSUE TITLE
Can't run phpexecjs on windows 10 , node.exe path

### ISSUE THREAD

**Issue by cAstraea** [nacmartin/phpexecjs#6]
Not sure why it's looking for node in  C:\Program Files\nodejs\node.exe to run C:\Users\Razva\AppData\Local\Temp\nacmartin_phpexecjs57e3ab3f331e49.24296671.js
It's installed globally ? Guess could just run node ? Seems the space in Program Files is the culprit ?

> The exit status code '1' says something went wrong:
> stderr: "'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> "
> stdout: ""
> command: C:\Program Files\nodejs\node.exe C:\Users\Razva\AppData\Local\Temp\nacmartin_phpexecjs57e3ab3f331e49.24296671.js.

**Comment by cAstraea** [comment]
Not sure if this is helpful , found this https://github.com/npm/how-to-npm/issues/11

Apparently there's a which package that doesn't return the correct path so maybe would need to define var node = "node" somewhere ?

**Comment by cAstraea** [comment]
Think found my issue but may be just an edge case ... I replaced $command = 'node'; in public function evalJS($code) in ExternalRuntime.php

**Comment by nacmartin** [comment]
Uhm... Windows 10. Can you verify if this fixes it for you? https://github.com/nacmartin/phpexecjs/pull/5

It is difficult for me to test it in Windows 10, as I have no access to a machine with Windows 10. If you find a solution that can help others, any help would be appreciated :-)

**Comment by cAstraea** [comment]
Hello , had no problem on my machine with PHP_WINDOWS_VERSION_MAJOR :-) Both detected (PHP_OS, version_major)

Just node was living in Program Files path so would need to use short path Progra~1 or wrap it in double quotes before executing the command.

 Made a PR for this.

**Comment by nacmartin** [comment]
This was fixed in https://github.com/nacmartin/phpexecjs/pull/7
